### ISSUE TITLE
 pip install . is failed

### ISSUE THREAD

**Issue by D-jojo** [google-deepmind/language_to_reward_2023#5]
Hi, @fxia22 
I have encountered the following problem that I have been trying for a long time but still cannot solve. Please help me.

[ 95%] Built target grpc
      make[1]: *** [CMakeFiles/Makefile2:9821: mjpc/CMakeFiles/l2r_headless_server.dir/rule] Error 2
      make: *** [Makefile:2761: l2r_headless_server] Error 2
      Configuring CMake with the following arguments:
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DBUILD_TESTING:BOOL=OFF
      Building `l2r_headless_server` and `l2r_ui_server` with CMake
      Traceback (most recent call last):
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 179, in <module>
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-og3_5ice/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "<string>", line 50, in run
        File "<string>", line 93, in _configure_and_build_agent_server
        File "/root/miniconda3/envs/l2reward/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '/root/language_to_reward_2023/build', '--target', 'l2r_headless_server', 'l2r_ui_server', '-j24', '--config', 'Debug']' returned non-zero exit status 2.
      [end of output]

**Comment by nimrod-gileadi** [comment]
Are you using the exact installation instructions given in the repository README? From the error logs it looks like you're using Conda, which we haven't tested with.

Please add the `-v` flag to `pip install` and paste the full error logs.

Also, tell us what platform you're working with (mac or linux, version)

**Comment by D-jojo** [comment]
Thank you for your reply. I am using Linux. I have resolved the compilation issue.
The following is my error message, which I resolved by modifying the. cc file.

[ 98%] Built target agent_service_proto_lib
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc: In member function ‘virtual void mjpc::Batch::GUI(mjUI&)’:
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:976:66: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        976 |   defProcessNoise[0] = {mjITEM_SEPARATOR, "Process Noise Std.", 1};
            |                                                                  ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/estimators/batch.h:23,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:983:78: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        983 |         mjITEM_SLIDERNUM, "", 2, gui_process_noise_.data() + i, "1.0e-8 0.01"};
            |                                                                              ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/estimators/batch.h:23,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:1091:64: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
       1091 |   defSensorNoise[0] = {mjITEM_SEPARATOR, "Sensor Noise Std.", 1};
            |                                                                ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/estimators/batch.h:23,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:1103:73: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
       1103 |         gui_sensor_noise_.data() + sensor_noise_shift - 1, "1.0e-8 0.01"};
            |                                                                         ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/estimators/batch.h:23,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/estimators/batch.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      make[3]: *** [_deps/mjpc-build/mjpc/CMakeFiles/libmjpc.dir/build.make:518: _deps/mjpc-build/mjpc/CMakeFiles/libmjpc.dir/estimators/batch.cc.o] Error 1
      make[3]: *** Waiting for unfinished jobs....
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc: In member function ‘void mjpc::Agent::GUI(mjUI&)’:
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:597:46: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        597 |        DataAt(ActiveTask()->weight, i), "0 1"};
            |                                              ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/agent.h:27,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:616:65: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        616 |     defFeatureParameters[0] = {mjITEM_SEPARATOR, "Parameters", 1};
            |                                                                 ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/agent.h:27,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:621:14: error: no match for ‘operator=’ (operand types are ‘mjuiDef’ {aka ‘mjuiDef_’} and ‘<brace-enclosed initializer list>’)
        621 |         "0 1"};
            |              ^
      In file included from /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mujoco.h:41,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/../mjpc/agent.h:27,
                       from /root/language_to_reward_2023/build/_deps/mjpc-src/mjpc/agent.cc:15:
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(const mjuiDef_&)’
        312 | struct mjuiDef_ {                 // table passed to mjui_add()
            |        ^~~~~~~~
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const mjuiDef_&’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note: candidate: ‘constexpr mjuiDef_& mjuiDef_::operator=(mjuiDef_&&)’
      /root/language_to_reward_2023/build/_deps/mujoco-src/include/mujoco/mjui.h:312:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘mjuiDef_&&’
      make[3]: *** [_deps/mjpc-build/mjpc/CMakeFiles/libmjpc.dir/build.make:76: _deps/mjpc-build/mjpc/CMakeFiles/libmjpc.dir/agent.cc.o] Error 1
      make[2]: *** [CMakeFiles/Makefile2:6379: _deps/mjpc-build/mjpc/CMakeFiles/libmjpc.dir/all] Error 2
      make[1]: *** [CMakeFiles/Makefile2:9821: mjpc/CMakeFiles/l2r_headless_server.dir/rule] Error 2
      make: *** [Makefile:2761: l2r_headless_server] Error 2
      Configuring CMake with the following arguments:
        -DCMAKE_BUILD_TYPE:STRING=Debug
        -DBUILD_TESTING:BOOL=OFF
      Building `l2r_headless_server` and `l2r_ui_server` with CMake
      Traceback (most recent call last):
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/miniconda3/envs/l2reward/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 415, in build_wheel
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 179, in <module>
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 964, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/command/bdist_wheel.py", line 373, in run
          self.run_command("build")
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 945, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-zqa0xks0/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 983, in run_command
          cmd_obj.run()
        File "<string>", line 50, in run
        File "<string>", line 93, in _configure_and_build_agent_server
        File "/root/miniconda3/envs/l2reward/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '--build', '/root/language_to_reward_2023/build', '--target', 'l2r_headless_server', 'l2r_ui_server', '-j24', '--config', 'Debug']' returned non-zero exit status 2.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for language_to_reward_2023
Failed to build language_to_reward_2023
ERROR: Could not build wheels for language_to_reward_2023, which is required to install pyproject.toml-based projects

**Comment by D-jojo** [comment]
I have encountered a new problem now.
The program I am running in Docker，ubuntu20.04 python3.10
When I execute python - m language_to-reward_2023. user_interaction -- api_key=<Open AI API key>
The following is the error message:


(l2reward) root@14f5f581745f:~/language_to_reward_2023# python -m language_to_reward_2023.user_interaction --api_key=<Open AI API key>
Starting MJPC UI
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723639466.629073  112529 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
MuJoCo MPC (MJPC)
 MuJoCo version 3.0.1
 Hardware threads:  24
I0000 00:00:1723639466.639023  112555 subchannel.cc:806] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-08-14T20:44:26.638903324+08:00"}), backing off for 1000 ms
I0000 00:00:1723639467.639456  112559 subchannel.cc:761] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: backoff delay elapsed, reporting IDLE
I0000 00:00:1723639467.640042  112555 subchannel.cc:806] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-08-14T20:44:27.639812339+08:00"}), backing off for 1641 ms
I0000 00:00:1723639469.281753  112569 subchannel.cc:761] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: backoff delay elapsed, reporting IDLE
I0000 00:00:1723639469.282337  112555 subchannel.cc:806] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: connect failed (UNKNOWN:Failed to connect to remote host: connect: Connection refused (111) {created_time:"2024-08-14T20:44:29.282118253+08:00"}), backing off for 3015 ms
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723639470.076276  112554 ui_server.cc:54] Server listening on [::]:58311
  physics        :  1
  render         :  1
  Planner        :  1
    planning     :  21
  Estimator      :  0
    estimation   :  0
ERROR: mjui_add: data pointer for item without data

Press Enter to exit ...I0000 00:00:1723639472.298483  112564 subchannel.cc:761] subchannel 0x78caf0001290 {address=ipv4:127.0.0.1:58311, args={grpc.client_channel_factory=0xe95150, grpc.default_authority=localhost:58311, grpc.internal.channel_credentials=0x1a28890, grpc.internal.client_channel_call_destination=0x78cb0d3703d0, grpc.internal.event_engine=0x78caf00143c0, grpc.internal.security_connector=0x78caf0013630, grpc.internal.subchannel_pool=0x188afa0, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x1a50700, grpc.server_uri=dns:///localhost:58311}}: backoff delay elapsed, reporting IDLE

**Comment by D-jojo** [comment]
I'm having this problem now.

(l2reward) root@14f5f581745f:~/language_to_reward_2023# python -m language_to_reward_2023.user_interaction --api_key=sk-
Starting MJPC UI
MuJoCo MPC (MJPC)
 MuJoCo version 3.0.1
 Hardware threads:  24
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1723797881.792872  117467 ui_server.cc:54] Server listening on [::]:58411
  physics        :  1
  render         :  1
  Planner        :  1
    planning     :  21
  Estimator      :  0
    estimation   :  0
ERROR: mjui_add: data pointer for item without data
